# Base configs
baseurl: "http://richardtcle.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-123291677-1"

# UI configs
title: "Photography by Richard Le"
subtitle: "Photos of places and people I love"
author: "Richard Le"
header:
 title: "Snapshots"
 subtitle: "by Richard Le"
footer:
 name: "Hello! My name is Richard Le"
 bio: "I am a new Computer Science graduate with a passion for photography. Here I will post pictures shot and edited by me. Sony a7rII"
social_urls:
  facebook: "https://www.facebook.com/richardtcle"
  instagram: "https://www.instagram.com/richardtcle"
  linkedin: "https://www.linkedin.com/in/richardle311"
  github: "https://github.com/richardtcle"
